Update commit-move.yml

diff --git a/.github/workflows/commit-move.yml b/.github/workflows/commit-move.yml
--- a/.github/workflows/commit-move.yml
+++ b/.github/workflows/commit-move.yml
@@ -58,9 +58,15 @@ jobs:
           
           echo read release file
 
-          while IFS= read -r release; do
-              echo "Creating GitHub release for $release"
-              gh release create "$release" --title "$release" --latest false
+          if [[ ! -f releases.txt ]]; then
+              echo "releases.txt not found!"
+              exit 1
+          fi
+          
+          # Read the contents of releases.txt and echo each line
+          while IFS= read -r line; do
+              echo "$line"
+              gh release create "$line" --title "$line" --latest false
           done < releases.txt
           
         continue-on-error: true
